export const LEITFRAGEN_PAGES = [
  {
    key: 'dream_life',
    title: 'Wie würde dein absolutes Traumleben aussehen?',
    eyebrow: 'Frage 01',
    prompts: [
      'Wie würde deine finanzielle Situation aussehen?',
      'Wie würde dein Körper aussehen? Wie gesund, fit und leistungsfähig wärst du?',
      'Mit welchen Menschen würdest du dein Leben verbringen? Wie würde deine Traumfrau oder dein Traummann aussehen? Wie viele Kinder hättest du? Wie wäre dein Verhältnis zu deiner Familie und deinen Freunden? Würdest du Haustiere besitzen?',
      'Was für ein Mensch wärst du? Welche Eigenschaften würdest du besitzen?',
      'Wie würdest du wollen, dass dich andere Menschen wahrnehmen oder beschreiben? Soll man dich respektieren, bewundern, als Vorbild ansehen oder von deiner Ausstrahlung beeindruckt sein?',
      'Würdest du überhaupt noch arbeiten wollen? Wenn ja, welcher Tätigkeit würdest du nachgehen? Oder würdest du lieber eine Stiftung gründen, anderen Menschen helfen oder auf eine andere Weise einen positiven Einfluss auf die Welt haben?',
      'Wo würdest du leben? Wie würde dein Haus aussehen? Welche Autos würdest du fahren? Würdest du eine Yacht, einen Privatjet oder andere Luxusgüter besitzen wollen?',
      'Welche Orte auf der Welt möchtest du sehen? Welche Erfahrungen möchtest du unbedingt gemacht haben? Welche Erlebnisse dürfen in deinem Leben auf keinen Fall fehlen?',
      'Was möchtest du deinen Kindern, deiner Familie oder der Welt hinterlassen? Wie möchtest du in Erinnerung bleiben? Welches Vermächtnis möchtest du einmal hinterlassen?',
    ],
    placeholder: 'Schreibe hier dein absolutes Traumleben auf. Je konkreter, desto stärker wird diese Seite.',
    exampleAnswer: '',
  },
  {
    key: 'best_life_moments',
    title: 'Was waren bisher die schönsten Momente deines Lebens?',
    eyebrow: 'Frage 02',
    prompts: [
      'Wann warst du in deinem Leben am glücklichsten?',
      'Welche Momente haben dich besonders erfüllt?',
      'Mit welchen Menschen warst du zusammen?',
      'Was genau hat diese Momente so besonders gemacht?',
      'Welche Gefühle hast du dabei gespürt?',
      'Welche Erlebnisse würdest du sofort noch einmal erleben wollen?',
    ],
    placeholder: 'Schreibe die schönsten Momente deines Lebens auf und beschreibe, warum sie für dich so besonders waren.',
    exampleAnswer: '',
  },
  {
    key: 'deepest_gratitude',
    title: 'Wofür bist du in deinem Leben am dankbarsten?',
    eyebrow: 'Frage 03',
    prompts: [
      'Für welche Menschen in deinem Leben bist du dankbar?',
      'Für welche Momente bist du dankbar?',
      'Welche Dinge hältst du vielleicht für selbstverständlich, für die du aber dennoch dankbar bist?',
      'Nenne mindestens 20 Dinge.',
    ],
    placeholder: 'Schreibe mindestens 20 Dinge auf, für die du wirklich dankbar bist.',
    exampleAnswer: '',
  },
  {
    key: 'proudest_achievements',
    title: 'Worauf bist du in deinem Leben bisher am meisten stolz?',
    eyebrow: 'Frage 04',
    prompts: [
      'Welche Erfolge hast du bereits erreicht?',
      'Welche Herausforderungen hast du überwunden?',
      'Welche schwierigen Situationen hast du gemeistert?',
      'Was hast du erreicht, obwohl andere vielleicht nicht an dich geglaubt haben?',
      'Welche Eigenschaften haben dir dabei geholfen?',
    ],
    placeholder: 'Schreibe auf, worauf du wirklich stolz bist und welche Eigenschaften dich dorthin gebracht haben.',
    exampleAnswer: '',
  },
  {
    key: 'biggest_strengths',
    title: 'Was sind deine größten Stärken?',
    eyebrow: 'Frage 05',
    prompts: [
      'Worin bist du besonders gut?',
      'Welche Talente besitzt du?',
      'Was fällt dir leichter als anderen Menschen?',
      'Wofür wirst du häufig gelobt?',
      'Welche Fähigkeiten möchtest du weiterentwickeln?',
      'Welche Stärken helfen dir dabei, dein Traumleben zu erreichen?',
    ],
    placeholder: 'Schreibe deine wichtigsten Stärken auf und verbinde sie mit deinem zukünftigen Leben.',
    exampleAnswer: '',
  },
  {
    key: 'where_one_month',
    title: 'Wo sehe ich mich in 1 Monat?',
    eyebrow: 'Frage 06',
    prompts: [],
    placeholder: 'Schreibe hier auf, wo du dich in 1 Monat siehst.',
    exampleAnswer: '',
  },
  {
    key: 'where_three_years',
    title: 'Wo sehe ich mich in 3 Jahren?',
    eyebrow: 'Frage 07',
    prompts: [],
    placeholder: 'Schreibe hier auf, wo du dich in 3 Jahren siehst.',
    exampleAnswer: '',
  },
  {
    key: 'where_ten_years',
    title: 'Wo sehe ich mich in 10 Jahren?',
    eyebrow: 'Frage 08',
    prompts: [],
    placeholder: 'Schreibe hier auf, wo du dich in 10 Jahren siehst.',
    exampleAnswer: '',
  },
];

export function getLeitfragenPageIndex(page) {
  if (!page?.key) return -1;
  return LEITFRAGEN_PAGES.findIndex(item => item.key === page.key);
}
