import { StyleSheet } from 'react-native';

import { COLORS } from '../../../../constants/colors';
import { s, sv, sf } from '../../../../constants/layout';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  topBar: {
    paddingTop: sv(58),
    paddingHorizontal: s(20),
    paddingBottom: sv(8),
  },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(4),
  },
  backText: {
    color: COLORS.softGold,
    fontSize: sf(16),
    fontWeight: '700',
  },
  content: {
    paddingHorizontal: s(20),
    paddingBottom: sv(36),
  },
  header: {
    alignItems: 'center',
    paddingTop: sv(10),
    marginBottom: sv(22),
  },
  iconCircle: {
    width: s(78),
    height: s(78),
    borderRadius: s(39),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.darkCard,
    marginBottom: sv(14),
  },
  title: {
    color: COLORS.textPrimary,
    fontSize: sf(30),
    fontWeight: '900',
    letterSpacing: 2,
  },
  subtitle: {
    color: COLORS.textMuted,
    fontSize: sf(13),
    marginTop: sv(6),
    textAlign: 'center',
  },
  infoCard: {
    borderWidth: 1,
    borderColor: COLORS.toolsCardBorderActive,
    backgroundColor: COLORS.toolsCard,
    borderRadius: s(22),
    padding: s(16),
    marginBottom: sv(16),
  },
  infoTitle: {
    color: COLORS.softGold,
    fontSize: sf(15),
    fontWeight: '800',
    marginBottom: sv(4),
  },
  infoText: {
    color: COLORS.textDim,
    fontSize: sf(12),
    lineHeight: sf(18),
  },
  dayRow: {
    flexDirection: 'row',
    gap: s(8),
    marginBottom: sv(18),
  },
  dayBtn: {
    flex: 1,
    minHeight: sv(58),
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    backgroundColor: COLORS.darkCard,
    borderRadius: s(16),
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: sv(8),
  },
  dayBtnActive: {
    borderColor: COLORS.goldBorderLight,
    backgroundColor: COLORS.darkCard2,
  },
  dayLabel: {
    color: COLORS.textDim,
    fontSize: sf(10),
    fontWeight: '800',
  },
  dayLabelActive: {
    color: COLORS.softGold,
  },
  dayDate: {
    color: COLORS.textFaint,
    fontSize: sf(10),
    marginTop: sv(3),
  },
  dayDateActive: {
    color: COLORS.gold,
  },
  dayDot: {
    width: s(5),
    height: s(5),
    borderRadius: s(2.5),
    backgroundColor: COLORS.gold,
    marginTop: sv(5),
  },
  errorCard: {
    borderWidth: 1,
    borderColor: 'rgba(212, 106, 106, 0.35)',
    backgroundColor: 'rgba(212, 106, 106, 0.08)',
    borderRadius: s(16),
    padding: s(14),
    marginBottom: sv(14),
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    borderWidth: 1,
    borderColor: 'rgba(212, 106, 106, 0.35)',
    backgroundColor: 'rgba(212, 106, 106, 0.08)',
    borderRadius: s(14),
    padding: s(12),
    marginBottom: sv(14),
  },
  errorText: {
    flex: 1,
    color: COLORS.errorLight,
    fontSize: sf(12),
  },
  retryBtn: {
    marginTop: sv(10),
    alignSelf: 'flex-start',
    paddingHorizontal: s(12),
    paddingVertical: sv(7),
    borderRadius: s(999),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
  },
  retryText: {
    color: COLORS.softGold,
    fontSize: sf(12),
    fontWeight: '800',
  },
  formCard: {
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    backgroundColor: COLORS.darkCard2,
    borderRadius: s(24),
    padding: s(16),
    marginBottom: sv(20),
  },
  formHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: sv(14),
  },
  formTitle: {
    color: COLORS.textPrimary,
    fontSize: sf(16),
    fontWeight: '900',
  },
  cancelText: {
    color: COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '800',
  },
  questionBlock: {
    marginBottom: sv(14),
  },
  questionText: {
    color: COLORS.softGold,
    fontSize: sf(13),
    fontWeight: '800',
    marginBottom: sv(8),
  },
  input: {
    minHeight: sv(76),
    borderWidth: 1,
    borderColor: COLORS.borderMid,
    backgroundColor: COLORS.backgroundCard,
    borderRadius: s(16),
    color: COLORS.textSecondary,
    paddingHorizontal: s(12),
    paddingVertical: sv(10),
    fontSize: sf(13),
    textAlignVertical: 'top',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
    marginBottom: sv(12),
  },
  checkbox: {
    width: s(24),
    height: s(24),
    borderRadius: s(8),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.backgroundCard,
  },
  checkboxActive: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
  },
  checkboxText: {
    flex: 1,
    color: COLORS.textSecondary,
    fontSize: sf(13),
    fontWeight: '700',
  },
  saveButton: {
    minHeight: sv(48),
    borderRadius: s(999),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    backgroundColor: 'rgba(212, 175, 55, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: sv(4),
  },
  saveButtonDisabled: {
    opacity: 0.45,
  },
  saveText: {
    color: COLORS.softGold,
    fontSize: sf(14),
    fontWeight: '900',
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(12),
  },
  sectionTitle: {
    color: COLORS.textPrimary,
    fontSize: sf(15),
    fontWeight: '900',
    letterSpacing: 1,
  },
  sectionCount: {
    color: COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    borderRadius: s(22),
    padding: s(24),
    backgroundColor: COLORS.darkCard,
    marginBottom: sv(18),
  },
  emptyText: {
    color: COLORS.textSecondary,
    fontSize: sf(15),
    fontWeight: '800',
    marginTop: sv(10),
  },
  emptySubText: {
    color: COLORS.textDim,
    fontSize: sf(12),
    marginTop: sv(4),
    textAlign: 'center',
  },
  list: {
    gap: sv(12),
  },
  entryCard: {
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    backgroundColor: COLORS.darkCard,
    borderRadius: s(22),
    padding: s(15),
  },
  entryHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(10),
  },
  entryTime: {
    color: COLORS.gold,
    fontSize: sf(12),
    fontWeight: '900',
  },
  entryActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(12),
  },
  entryQuestion: {
    color: COLORS.softGold,
    fontSize: sf(12),
    fontWeight: '800',
    marginTop: sv(9),
  },
  entryAnswer: {
    color: COLORS.textSecondary,
    fontSize: sf(13),
    lineHeight: sf(19),
    marginTop: sv(3),
  },
  habitsDone: {
    color: COLORS.textSecondary,
    fontSize: sf(13),
    fontWeight: '700',
    marginTop: sv(10),
  },
});