import { StyleSheet } from 'react-native';

import { COLORS } from '../../../../constants/colors';
import { s, sv, sf } from '../../../../constants/layout';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  background: {
    flex: 1,
  },
  backgroundImage: {
    opacity: 1,
  },
  backgroundOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 4, 10, 0.50)',
  },
  topBar: {
    paddingTop: sv(58),
    paddingHorizontal: s(20),
    paddingBottom: sv(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(4),
  },
  backText: {
    color: COLORS.softGold,
    fontSize: sf(16),
    fontWeight: '700',
  },
  tocTopButton: {
    minWidth: s(86),
    height: s(38),
    borderRadius: s(19),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    backgroundColor: 'rgba(10, 9, 17, 0.64)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(4),
  },
  tocTopText: {
    color: COLORS.softGold,
    fontSize: sf(12),
    fontWeight: '900',
  },
  gestureArea: {
    flex: 1,
  },
  content: {
    paddingHorizontal: s(20),
    paddingBottom: sv(36),
  },
  header: {
    alignItems: 'center',
    paddingTop: 0,
    marginBottom: sv(14),
  },
  iconCircle: {
    width: s(72),
    height: s(72),
    borderRadius: s(36),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(10, 9, 17, 0.72)',
    marginBottom: sv(12),
  },
  title: {
    color: COLORS.textPrimary,
    fontSize: sf(30),
    fontWeight: '900',
    letterSpacing: 2,
  },
  subtitle: {
    color: COLORS.textMuted,
    fontSize: sf(13),
    marginTop: sv(6),
    textAlign: 'center',
  },
  pageNavCard: {
    position: 'relative',
    zIndex: 20,
    elevation: 20,
    minHeight: sv(76),
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    backgroundColor: 'rgba(10, 9, 17, 0.68)',
    borderRadius: s(24),
    padding: s(10),
    marginBottom: sv(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pageArrowButton: {
    width: s(48),
    height: s(48),
    borderRadius: s(24),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageNavCenter: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: s(12),
  },
  pageNavTitleRow: {
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageNavKicker: {
    color: COLORS.gold,
    fontSize: sf(11),
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  pageNavTitle: {
    color: COLORS.textPrimary,
    fontSize: sf(16),
    fontWeight: '900',
    marginTop: sv(4),
  },
  pageTurnWrap: {
    width: '100%',
    position: 'relative',
    zIndex: 1,
    elevation: 1,
    overflow: 'hidden',
    borderRadius: s(28),
    backfaceVisibility: 'hidden',
  },
  pageTurnShadow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: s(28),
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
    zIndex: 2,
  },
  pageTurnFold: {
    position: 'absolute',
    top: sv(8),
    bottom: sv(8),
    width: s(24),
    right: s(16),
    borderRadius: s(999),
    backgroundColor: 'rgba(255, 236, 170, 0.14)',
    zIndex: 3,
  },
  bookPageCard: {
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    backgroundColor: 'rgba(14, 13, 22, 0.78)',
    borderRadius: s(28),
    padding: s(17),
    marginBottom: sv(20),
    overflow: 'hidden',
  },
  pageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(12),
  },
  pageBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    borderRadius: s(999),
    paddingHorizontal: s(11),
    paddingVertical: sv(6),
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
  },
  pageBadgeText: {
    color: COLORS.softGold,
    fontSize: sf(11),
    fontWeight: '900',
  },
  pageEntryCount: {
    color: COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '800',
  },
  bookPageTitle: {
    color: COLORS.textPrimary,
    fontSize: sf(23),
    fontWeight: '900',
    lineHeight: sf(29),
    marginBottom: sv(7),
  },
  bookPageDescription: {
    color: COLORS.textDim,
    fontSize: sf(13),
    lineHeight: sf(20),
    marginBottom: sv(17),
  },
  questionBlock: {
    marginBottom: sv(14),
  },
  questionText: {
    color: COLORS.softGold,
    fontSize: sf(13),
    fontWeight: '800',
    marginBottom: sv(8),
  },
  input: {
    minHeight: sv(76),
    borderWidth: 1,
    borderColor: COLORS.borderMid,
    backgroundColor: 'rgba(8, 7, 14, 0.64)',
    borderRadius: s(16),
    color: COLORS.textSecondary,
    paddingHorizontal: s(12),
    paddingVertical: sv(10),
    fontSize: sf(13),
    lineHeight: sf(19),
    textAlignVertical: 'top',
  },
  starterInput: {
    minHeight: sv(230),
    marginBottom: sv(14),
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
    marginBottom: sv(12),
  },
  checkbox: {
    width: s(24),
    height: s(24),
    borderRadius: s(8),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8, 7, 14, 0.62)',
  },
  checkboxActive: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
  },
  checkboxText: {
    flex: 1,
    color: COLORS.textSecondary,
    fontSize: sf(13),
    fontWeight: '700',
  },
  cancelEditButton: {
    alignSelf: 'flex-start',
    marginBottom: sv(10),
  },
  cancelText: {
    color: COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '800',
  },
  saveButton: {
    minHeight: sv(48),
    borderRadius: s(999),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    backgroundColor: 'rgba(212, 175, 55, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: sv(4),
  },
  saveButtonDisabled: {
    opacity: 0.45,
  },
  saveText: {
    color: COLORS.softGold,
    fontSize: sf(14),
    fontWeight: '900',
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(12),
  },
  sectionTitle: {
    color: COLORS.textPrimary,
    fontSize: sf(15),
    fontWeight: '900',
    letterSpacing: 1,
  },
  sectionCount: {
    color: COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    borderRadius: s(22),
    padding: s(24),
    backgroundColor: 'rgba(10, 9, 17, 0.72)',
    marginBottom: sv(18),
  },
  emptyText: {
    color: COLORS.textSecondary,
    fontSize: sf(15),
    fontWeight: '800',
    marginTop: sv(10),
  },
  emptySubText: {
    color: COLORS.textDim,
    fontSize: sf(12),
    marginTop: sv(4),
    textAlign: 'center',
  },
  list: {
    gap: sv(12),
  },
  entryCard: {
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    backgroundColor: 'rgba(10, 9, 17, 0.72)',
    borderRadius: s(22),
    padding: s(15),
  },
  entryHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(10),
  },
  entryTime: {
    color: COLORS.gold,
    fontSize: sf(12),
    fontWeight: '900',
  },
  entryActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(12),
  },
  entryQuestion: {
    color: COLORS.softGold,
    fontSize: sf(12),
    fontWeight: '800',
    marginTop: sv(9),
  },
  entryAnswer: {
    color: COLORS.textSecondary,
    fontSize: sf(13),
    lineHeight: sf(19),
    marginTop: sv(3),
  },
  habitsDone: {
    color: COLORS.textSecondary,
    fontSize: sf(13),
    fontWeight: '700',
    marginTop: sv(10),
  },
  errorCard: {
    borderWidth: 1,
    borderColor: 'rgba(212, 106, 106, 0.35)',
    backgroundColor: 'rgba(212, 106, 106, 0.08)',
    borderRadius: s(16),
    padding: s(14),
    marginBottom: sv(14),
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    borderWidth: 1,
    borderColor: 'rgba(212, 106, 106, 0.35)',
    backgroundColor: 'rgba(212, 106, 106, 0.08)',
    borderRadius: s(14),
    padding: s(12),
    marginBottom: sv(14),
  },
  errorText: {
    flex: 1,
    color: COLORS.errorLight,
    fontSize: sf(12),
    lineHeight: sf(17),
  },
  retryBtn: {
    marginTop: sv(10),
    alignSelf: 'flex-start',
    paddingHorizontal: s(12),
    paddingVertical: sv(7),
    borderRadius: s(999),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
  },
  retryText: {
    color: COLORS.softGold,
    fontSize: sf(12),
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.80)',
    paddingHorizontal: s(18),
    justifyContent: 'center',
  },
  tocModal: {
    maxHeight: '82%',
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    backgroundColor: 'rgba(10, 9, 17, 0.94)',
    borderRadius: s(28),
    padding: s(17),
  },
  tocHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(16),
  },
  tocTitle: {
    color: COLORS.textPrimary,
    fontSize: sf(21),
    fontWeight: '900',
  },
  tocSubtitle: {
    color: COLORS.textDim,
    fontSize: sf(12),
    marginTop: sv(3),
  },
  tocContent: {
    paddingBottom: sv(8),
  },
  tocSectionLabel: {
    color: COLORS.gold,
    fontSize: sf(11),
    fontWeight: '900',
    letterSpacing: 1.2,
    marginTop: sv(10),
    marginBottom: sv(8),
  },
  tocItem: {
    minHeight: sv(58),
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    backgroundColor: 'rgba(18, 16, 28, 0.72)',
    borderRadius: s(18),
    paddingHorizontal: s(12),
    paddingVertical: sv(10),
    marginBottom: sv(9),
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
  },
  tocItemIcon: {
    width: s(34),
    height: s(34),
    borderRadius: s(17),
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tocItemIconMuted: {
    borderColor: COLORS.borderSubtle,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  tocItemNumber: {
    color: COLORS.gold,
    fontSize: sf(11),
    fontWeight: '900',
  },
  tocItemTextWrap: {
    flex: 1,
  },
  tocItemTitle: {
    color: COLORS.textPrimary,
    fontSize: sf(13),
    fontWeight: '900',
  },
  tocItemSubtitle: {
    color: COLORS.textDim,
    fontSize: sf(11),
    marginTop: sv(3),
  },
  tocDot: {
    width: s(7),
    height: s(7),
    borderRadius: s(3.5),
    backgroundColor: COLORS.gold,
  },
  calendarModal: {
    borderWidth: 1,
    borderColor: COLORS.goldBorderLight,
    backgroundColor: 'rgba(10, 9, 17, 0.99)',
    borderRadius: s(28),
    padding: s(17),
  },
  datePicker: {
    alignSelf: 'stretch',
    backgroundColor: 'rgba(15, 13, 22, 0.98)',
    borderRadius: s(18),
  },
});
