import { StyleSheet } from 'react-native';

import { COLORS } from '../../../../constants/colors';
import { s, sv, sf } from '../../../../constants/layout';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  topBar: {
    position: 'absolute',
    top: sv(54),
    left: s(16),
    zIndex: 10,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(4),
  },
  backText: {
    color: COLORS.softGold,
    fontSize: sf(16),
    fontWeight: '600',
  },
  idleContent: {
    paddingTop: sv(110),
    paddingHorizontal: s(20),
    paddingBottom: sv(100),
    alignItems: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: sv(32),
  },
  iconCircle: {
    width: s(80),
    height: s(80),
    borderRadius: s(40),
    borderWidth: 1.5,
    borderColor: COLORS.gold,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sv(16),
    backgroundColor: 'rgba(212,175,55,0.08)',
  },
  title: {
    color: COLORS.paleGold,
    fontSize: sf(32),
    fontWeight: '800',
    letterSpacing: 3,
  },
  subtitle: {
    color: COLORS.textSecondary,
    fontSize: sf(13),
    textAlign: 'center',
    marginTop: sv(8),
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: s(10),
    borderWidth: 1,
    borderColor: 'rgba(212,175,55,0.25)',
    backgroundColor: 'rgba(212,175,55,0.05)',
    borderRadius: s(14),
    padding: s(14),
    marginBottom: sv(32),
    width: '100%',
  },
  infoText: {
    flex: 1,
    color: COLORS.textSecondary,
    fontSize: sf(13),
    lineHeight: sf(20),
  },
  startButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(10),
    backgroundColor: COLORS.gold,
    borderRadius: s(14),
    height: sv(54),
    width: '100%',
  },
  startButtonText: {
    color: COLORS.black,
    fontSize: sf(16),
    fontWeight: '700',
  },

  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  sheetScrollContent: {
    paddingBottom: sv(10),
  },
  sheet: {
    backgroundColor: COLORS.darkCard,
    borderTopLeftRadius: s(24),
    borderTopRightRadius: s(24),
    paddingHorizontal: s(20),
    paddingTop: sv(12),
    paddingBottom: sv(10),
    borderTopWidth: 1,
    borderColor: 'rgba(212,175,55,0.25)',
  },
  sheetHandle: {
    width: s(40),
    height: sv(4),
    borderRadius: 999,
    backgroundColor: COLORS.textDim,
    alignSelf: 'center',
    marginBottom: sv(20),
  },
  sheetTitle: {
    color: COLORS.paleGold,
    fontSize: sf(20),
    fontWeight: '700',
    marginBottom: sv(16),
  },
  label: {
    color: COLORS.textMuted,
    fontSize: sf(11),
    fontWeight: '600',
    letterSpacing: 1.2,
    marginBottom: sv(8),
    marginTop: sv(4),
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    borderRadius: s(12),
    paddingHorizontal: s(14),
    paddingVertical: sv(12),
    color: COLORS.white,
    fontSize: sf(15),
    marginBottom: sv(14),
  },
  pickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(212,175,55,0.2)',
    borderRadius: s(16),
    backgroundColor: 'rgba(255,255,255,0.03)',
    paddingHorizontal: s(12),
    marginBottom: sv(16),
    overflow: 'hidden',
  },
  pickerSeparator: {
    color: COLORS.textMuted,
    fontSize: sf(16),
    fontWeight: '600',
    marginHorizontal: s(4),
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(8),
    marginBottom: sv(10),
  },
  chip: {
    paddingHorizontal: s(12),
    paddingVertical: sv(7),
    borderRadius: s(8),
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  chipActive: {
    borderColor: COLORS.gold,
    backgroundColor: 'rgba(212,175,55,0.12)',
  },
  chipText: {
    color: COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '600',
  },
  chipTextActive: {
    color: COLORS.gold,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: s(10),
    marginTop: sv(8),
  },
  cancelBtn: {
    flex: 1,
    height: sv(50),
    borderRadius: s(12),
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    color: COLORS.textSecondary,
    fontSize: sf(15),
    fontWeight: '600',
  },
  confirmBtn: {
    flex: 2,
    height: sv(50),
    borderRadius: s(12),
    backgroundColor: COLORS.gold,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  confirmBtnDisabled: {
    opacity: 0.4,
  },
  confirmBtnText: {
    color: COLORS.black,
    fontSize: sf(15),
    fontWeight: '700',
  },

  sessionHeader: {
    alignItems: 'center',
    paddingTop: sv(80),
    gap: sv(8),
    paddingBottom: sv(8),
  },
  sessionBackButton: {
    position: 'absolute',
    top: sv(54),
    left: s(16),
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(4),
  },
  sessionBackButtonHidden: {
    opacity: 0,
  },
  timerBlock: {
    alignItems: 'center',
    paddingTop: sv(32),
    gap: sv(12),
  },
  timerText: {
    color: COLORS.gold,
    fontSize: sf(72),
    fontWeight: '300',
    letterSpacing: 2,
    fontVariant: ['tabular-nums'],
  },
  taskName: {
    color: COLORS.textSecondary,
    fontSize: sf(20),
    fontWeight: '500',
  },
  categoryBadge: {
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    borderRadius: s(6),
    paddingHorizontal: s(10),
    paddingVertical: sv(4),
  },
  categoryBadgeText: {
    color: COLORS.dimGold,
    fontSize: sf(11),
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  progressTrack: {
    height: sv(3),
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginHorizontal: s(32),
    borderRadius: 999,
    marginTop: sv(32),
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: COLORS.gold,
    borderRadius: 999,
  },
  controlArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pauseRingOuter: {
    width: s(120),
    height: s(120),
    borderRadius: s(60),
    borderWidth: 2,
    borderColor: COLORS.gold,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: s(18),
    elevation: 12,
  },
  pauseButton: {
    width: s(100),
    height: s(100),
    borderRadius: s(50),
    backgroundColor: 'rgba(212,175,55,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomArea: {
    paddingHorizontal: s(20),
    paddingBottom: sv(88),
  },
  endButton: {
    height: sv(54),
    borderRadius: s(14),
    borderWidth: 1,
    borderColor: 'rgba(212,175,55,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  endButtonText: {
    color: COLORS.textSecondary,
    fontSize: sf(16),
    fontWeight: '600',
  },
});