import { Platform, StyleSheet } from 'react-native';

import { COLORS } from '../../../../constants/colors';
import { s, sv, sf, SCREEN } from '../../../../constants/layout';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.toolsBg ?? COLORS.background,
  },
  background: {
    flex: 1,
  },
  backgroundImage: {
    opacity: 1,
  },
  backgroundOverlay: {
    flex: 1,
  },
  topBar: {
    paddingTop: sv(52),
    paddingHorizontal: s(18),
    paddingBottom: sv(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(3),
  },
  backText: {
    color: COLORS.softGold,
    fontSize: sf(14),
    fontWeight: '800',
  },
  topActions: {
    alignItems: 'center',
    gap: sv(7),
  },
  iconButton: {
    width: s(38),
    height: s(38),
    borderRadius: s(15),
    backgroundColor: 'rgba(255,241,210,0.06)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,241,210,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpButton: {
    width: s(30),
    height: s(30),
    borderRadius: s(12),
    backgroundColor: 'rgba(255,241,210,0.045)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,241,210,0.11)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    paddingHorizontal: s(18),
    paddingTop: sv(8),
    paddingBottom: sv(180),
  },
  header: {
    marginBottom: sv(18),
  },
  kicker: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(11),
    fontWeight: '900',
    letterSpacing: 1.2,
    marginBottom: sv(7),
  },
  title: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(SCREEN.isSmall ? 29 : 33),
    fontWeight: '900',
    letterSpacing: -0.7,
  },
  subtitle: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(13.5),
    lineHeight: sf(20),
    marginTop: sv(8),
    maxWidth: s(320),
  },
  heroCard: {
    overflow: 'hidden',
    backgroundColor: 'rgba(5, 5, 8, 0.72)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorderActive ?? COLORS.borderMid,
    borderRadius: s(24),
    padding: s(17),
    marginBottom: sv(22),
  },
  heroGlow: {
    position: 'absolute',
    top: -sv(44),
    right: -s(45),
    width: s(150),
    height: s(150),
    borderRadius: s(75),
    backgroundColor: 'rgba(231,201,138,0.13)',
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: sv(16),
  },
  heroLabel: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(12.5),
    fontWeight: '800',
  },
  heroValue: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(31),
    fontWeight: '900',
    marginTop: sv(2),
  },
  totalLabel: {
    color: COLORS.toolsTextDim ?? COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '700',
    marginTop: sv(2),
  },
  miniBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(6),
    paddingHorizontal: s(10),
    paddingVertical: sv(8),
    borderRadius: 999,
    backgroundColor: 'rgba(231,201,138,0.10)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(231,201,138,0.24)',
  },
  miniBadgeText: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(12),
    fontWeight: '900',
  },
  progressTrack: {
    height: sv(7),
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
    marginBottom: sv(15),
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
  },
  primaryButton: {
    height: sv(48),
    borderRadius: s(17),
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(8),
  },
  primaryButtonText: {
    color: COLORS.black,
    fontSize: sf(14),
    fontWeight: '900',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(12),
  },
  sectionTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(17),
    fontWeight: '900',
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
    padding: s(12),
    borderRadius: s(16),
    backgroundColor: 'rgba(255,122,122,0.09)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,122,122,0.22)',
    marginBottom: sv(14),
  },
  errorText: {
    flex: 1,
    color: COLORS.errorLight,
    fontSize: sf(12.5),
    fontWeight: '700',
    lineHeight: sf(18),
  },
  loadingBox: {
    paddingVertical: sv(42),
    alignItems: 'center',
    justifyContent: 'center',
  },
  affirmationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(5, 5, 8, 0.72)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorder ?? COLORS.borderDeep,
    borderRadius: s(21),
    padding: s(13),
    marginBottom: sv(11),
  },
  affirmationMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(12),
  },
  checkCircle: {
    width: s(30),
    height: s(30),
    borderRadius: s(15),
    borderWidth: 1,
    borderColor: 'rgba(255,241,210,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,241,210,0.04)',
  },
  checkCircleActive: {
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
    borderColor: COLORS.toolsGold ?? COLORS.gold,
  },
  affirmationTextWrap: {
    flex: 1,
  },
  affirmationText: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(15),
    lineHeight: sf(21),
    fontWeight: '800',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(7),
    marginTop: sv(7),
  },
  categoryText: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(12),
    fontWeight: '800',
  },
  dot: {
    color: COLORS.toolsTextDim ?? COLORS.textDim,
    fontSize: sf(12),
  },
  statusText: {
    color: COLORS.toolsTextDim ?? COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '700',
  },
  statusTextDone: {
    color: '#7EE7A2',
  },
  cardActionButton: {
    width: s(36),
    height: s(36),
    borderRadius: s(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: s(26),
    borderRadius: s(24),
    backgroundColor: 'rgba(5, 5, 8, 0.72)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorder ?? COLORS.borderDeep,
  },
  emptyTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(17),
    fontWeight: '900',
    marginTop: sv(12),
  },
  emptyText: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(13),
    lineHeight: sf(19),
    textAlign: 'center',
    marginTop: sv(6),
  },
  floatingButton: {
    position: 'absolute',
    left: s(20),
    right: s(20),

    // höher, damit der Button nicht hinter der Bottom-Nav liegt
    bottom: s(96),

    height: s(56),
    borderRadius: s(20),
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(8),

    shadowColor: COLORS.toolsGold ?? COLORS.gold,
    shadowOpacity: 0.22,
    shadowRadius: s(16),
    shadowOffset: { width: 0, height: s(8) },
    elevation: 8,
  },
  floatingButtonText: {
    color: COLORS.black,
    fontSize: sf(15),
    fontWeight: '900',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.46)',
    justifyContent: 'flex-end',
  },
  modalScroll: {
    flex: 1,
  },
  modalScrollContent: {
    flexGrow: 1,
    paddingTop: sv(24),
  },
  keyboardDismissSpacer: {
    flex: 1,
    minHeight: sv(24),
  },
  modalCard: {
    backgroundColor: 'rgba(5, 5, 8, 0.96)',
    borderTopLeftRadius: s(30),
    borderTopRightRadius: s(30),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorderActive ?? COLORS.borderMid,
    maxHeight: SCREEN.height * 0.84,
    paddingTop: s(20),
    paddingHorizontal: s(20),
    paddingBottom: Platform.OS === 'ios' ? sv(30) : sv(24),
  },
  modalCardKeyboard: {
    maxHeight: SCREEN.height * 0.58,
  },
  modalInnerScroll: {
    maxHeight: '100%',
  },
  modalInnerScrollContent: {
    paddingBottom: sv(4),
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(18),
  },
  modalTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(22),
    fontWeight: '900',
  },
  inputLabel: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(12.5),
    fontWeight: '800',
    marginBottom: sv(8),
  },
  input: {
    minHeight: sv(52),
    maxHeight: sv(92),
    borderRadius: s(15),
    backgroundColor: 'rgba(5, 5, 8, 0.95)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorder ?? COLORS.borderDeep,
    paddingHorizontal: s(14),
    paddingVertical: sv(12),
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(15),
    fontWeight: '700',
    lineHeight: sf(21),
    textAlignVertical: 'top',
    marginBottom: sv(17),
  },
  suggestionsScroll: {
    maxHeight: sv(128),
    marginBottom: sv(2),
  },
  suggestionsScrollKeyboard: {
    maxHeight: sv(112),
  },
  suggestionsRow: {
    gap: s(10),
    paddingRight: s(20),
    paddingTop: sv(2),
    paddingBottom: sv(16),
  },
  suggestionsRowKeyboard: {
    paddingBottom: sv(12),
  },
  suggestionChip: {
    width: s(258),
    minHeight: sv(112),
    borderRadius: s(18),
    backgroundColor: 'rgba(231,201,138,0.08)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(231,201,138,0.22)',
    paddingHorizontal: s(14),
    paddingVertical: sv(12),
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  suggestionChipKeyboard: {
    minHeight: sv(98),
  },
  suggestionCategory: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(11),
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: sv(7),
  },
  suggestionText: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(13),
    lineHeight: sf(18),
    fontWeight: '800',
    textAlign: 'center',
  },
  categoryWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(8),
    marginBottom: sv(22),
  },
  categoryPill: {
    paddingHorizontal: s(12),
    paddingVertical: sv(9),
    borderRadius: 999,
    backgroundColor: COLORS.toolsCardSoft ?? COLORS.darkCard2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorder ?? COLORS.borderDeep,
  },
  categoryPillActive: {
    backgroundColor: 'rgba(231,201,138,0.12)',
    borderColor: 'rgba(231,201,138,0.38)',
  },
  categoryPillText: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(12.5),
    fontWeight: '800',
  },
  categoryPillTextActive: {
    color: COLORS.toolsGold ?? COLORS.gold,
  },
  saveButton: {
    height: sv(53),
    borderRadius: s(19),
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonDisabled: {
    opacity: 0.45,
  },
  saveButtonText: {
    color: COLORS.black,
    fontSize: sf(15),
    fontWeight: '900',
  },
  helpBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.58)',
    padding: s(20),
    justifyContent: 'center',
  },
  helpCard: {
    maxHeight: '82%',
    borderRadius: s(28),
    backgroundColor: 'rgba(5, 5, 8, 0.72)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorderActive ?? COLORS.borderMid,
    padding: s(20),
  },
  helpContent: {
    paddingBottom: sv(4),
  },
  helpIntroBox: {
    flexDirection: 'row',
    gap: s(12),
    padding: s(14),
    borderRadius: s(20),
    backgroundColor: 'rgba(231,201,138,0.10)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(231,201,138,0.22)',
    marginBottom: sv(16),
  },
  helpIntroText: {
    flex: 1,
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(13.5),
    lineHeight: sf(20),
    fontWeight: '800',
  },
  helpStep: {
    flexDirection: 'row',
    gap: s(12),
    marginBottom: sv(15),
  },
  helpStepNumber: {
    width: s(28),
    height: s(28),
    borderRadius: s(14),
    overflow: 'hidden',
    textAlign: 'center',
    lineHeight: s(28),
    color: COLORS.black,
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(13),
    fontWeight: '900',
  },
  helpStepTextWrap: {
    flex: 1,
  },
  helpStepTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(14.5),
    fontWeight: '900',
    marginBottom: sv(4),
  },
  helpStepText: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(12.8),
    lineHeight: sf(19),
    fontWeight: '700',
  },
  helpExampleTitle: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(12),
    fontWeight: '900',
    marginTop: sv(3),
    marginBottom: sv(7),
  },
  helpExampleText: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(15),
    lineHeight: sf(22),
    fontWeight: '900',
  },
  repeatBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.68)',
    padding: s(22),
    justifyContent: 'center',
  },
  repeatModalCard: {
    minHeight: sv(430),
    borderRadius: s(32),
    backgroundColor: 'rgba(5, 5, 8, 0.72)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorderActive ?? COLORS.borderMid,
    padding: s(22),
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  repeatClose: {
    position: 'absolute',
    top: sv(18),
    right: s(18),
    width: s(40),
    height: s(40),
    borderRadius: s(16),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,241,210,0.06)',
  },
  repeatKicker: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(11.5),
    fontWeight: '900',
    letterSpacing: 1.1,
    marginBottom: sv(8),
  },
  repeatCounter: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(12.5),
    fontWeight: '800',
    marginBottom: sv(24),
  },
  repeatQuoteCard: {
    width: '100%',
    minHeight: sv(150),
    borderRadius: s(28),
    backgroundColor: 'rgba(231,201,138,0.10)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(231,201,138,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: s(22),
    marginBottom: sv(19),
  },
  repeatQuoteText: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(24),
    lineHeight: sf(33),
    textAlign: 'center',
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  repeatHint: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(13),
    lineHeight: sf(19),
    textAlign: 'center',
    marginBottom: sv(23),
  },
});
