import { StyleSheet } from 'react-native';

import { COLORS } from '../../../../constants/colors';
import { s, sv, sf, SCREEN } from '../../../../constants/layout';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  background: {
    flex: 1,
  },
  backgroundImage: {
    opacity: 1,
  },
  backgroundOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 4, 10, 0.56)',
  },
  topBar: {
    paddingTop: sv(52),
    paddingHorizontal: s(18),
    paddingBottom: sv(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(3),
  },
  backText: {
    color: COLORS.softGold,
    fontSize: sf(14),
    fontWeight: '800',
  },
  iconButton: {
    width: s(38),
    height: s(38),
    borderRadius: s(15),
    backgroundColor: 'rgba(255,241,210,0.06)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,241,210,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    paddingHorizontal: s(18),
    paddingTop: sv(8),
    paddingBottom: sv(118),
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: s(16),
    marginBottom: sv(18),
  },
  headerTextWrap: {
    flex: 1,
  },
  kicker: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(11),
    fontWeight: '900',
    letterSpacing: 1.2,
    marginBottom: sv(7),
  },
  title: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(SCREEN.isSmall ? 29 : 33),
    fontWeight: '900',
    letterSpacing: -0.7,
  },
  subtitle: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(13.5),
    lineHeight: sf(20),
    marginTop: sv(8),
    maxWidth: s(310),
  },
  headerIconWrap: {
    width: s(48),
    height: s(48),
    borderRadius: s(18),
    backgroundColor: 'rgba(231,201,138,0.12)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(231,201,138,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCard: {
    overflow: 'hidden',
    backgroundColor: 'rgba(10, 9, 17, 0.82)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorderActive ?? COLORS.borderMid,
    borderRadius: s(24),
    padding: s(17),
    marginBottom: sv(18),
  },
  heroGlow: {
    position: 'absolute',
    top: -sv(44),
    right: -s(45),
    width: s(150),
    height: s(150),
    borderRadius: s(75),
    backgroundColor: 'rgba(231,201,138,0.13)',
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: s(12),
    marginBottom: sv(14),
  },
  heroLabel: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(12.5),
    fontWeight: '800',
  },
  heroValue: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(31),
    fontWeight: '900',
    marginTop: sv(2),
  },
  heroSubtext: {
    color: COLORS.toolsTextDim ?? COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '700',
    marginTop: sv(2),
  },
  miniBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(6),
    paddingHorizontal: s(10),
    paddingVertical: sv(8),
    borderRadius: 999,
    backgroundColor: 'rgba(231,201,138,0.10)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(231,201,138,0.24)',
    alignSelf: 'flex-start',
  },
  miniBadgeText: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(12),
    fontWeight: '900',
  },
  heroQuote: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(16.5),
    lineHeight: sf(23),
    fontWeight: '900',
  },
  typeTabs: {
    flexDirection: 'row',
    gap: s(8),
    marginBottom: sv(22),
  },
  typeTab: {
    flex: 1,
    minHeight: sv(44),
    borderRadius: s(16),
    backgroundColor: 'rgba(14, 13, 22, 0.78)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorder ?? COLORS.borderDeep,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(6),
    paddingHorizontal: s(5),
  },
  typeTabActive: {
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
    borderColor: COLORS.toolsGold ?? COLORS.gold,
  },
  typeTabText: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(12.5),
    fontWeight: '900',
  },
  typeTabTextActive: {
    color: COLORS.black,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(12),
  },
  sectionTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(17),
    fontWeight: '900',
  },
  sectionCount: {
    color: COLORS.toolsTextDim ?? COLORS.textDim,
    fontSize: sf(12),
    fontWeight: '900',
  },
  recommendationCard: {
    backgroundColor: 'rgba(10, 9, 17, 0.82)',
    borderRadius: s(22),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorder ?? COLORS.borderDeep,
    padding: s(15),
    marginBottom: sv(12),
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: sv(13),
  },
  typeIconBox: {
    width: s(40),
    height: s(40),
    borderRadius: s(16),
    backgroundColor: 'rgba(231,201,138,0.10)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(231,201,138,0.24)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveCircle: {
    width: s(38),
    height: s(38),
    borderRadius: s(15),
    backgroundColor: 'rgba(14, 13, 22, 0.78)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorder ?? COLORS.borderDeep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveCircleActive: {
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
    borderColor: COLORS.toolsGold ?? COLORS.gold,
  },
  cardCategory: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(11.5),
    fontWeight: '900',
    letterSpacing: 0.5,
    marginBottom: sv(6),
    textTransform: 'uppercase',
  },
  cardTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(20),
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  cardCreator: {
    color: COLORS.toolsTextDim ?? COLORS.textDim,
    fontSize: sf(13),
    fontWeight: '800',
    marginTop: sv(4),
  },
  cardTagline: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(13.5),
    lineHeight: sf(20),
    marginTop: sv(10),
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(8),
    marginTop: sv(13),
  },
  metaPill: {
    paddingHorizontal: s(10),
    paddingVertical: sv(7),
    borderRadius: 999,
    backgroundColor: 'rgba(255,241,210,0.055)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,241,210,0.09)',
  },
  metaPillText: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(11.5),
    fontWeight: '800',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.52)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: 'rgba(10, 9, 17, 0.82)',
    borderTopLeftRadius: s(30),
    borderTopRightRadius: s(30),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorderActive ?? COLORS.borderMid,
    padding: s(20),
    paddingBottom: sv(32),
    maxHeight: '84%',
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: sv(10),
  },
  modalKicker: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: sf(11.5),
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  modalTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(27),
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  modalCreator: {
    color: COLORS.toolsTextDim ?? COLORS.textDim,
    fontSize: sf(13.5),
    fontWeight: '800',
    marginTop: sv(5),
  },
  modalMetaRow: {
    flexDirection: 'row',
    gap: s(8),
    marginTop: sv(16),
    marginBottom: sv(18),
  },
  modalSectionTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(14.5),
    fontWeight: '900',
    marginTop: sv(12),
    marginBottom: sv(7),
  },
  modalText: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(13.5),
    lineHeight: sf(20.5),
  },
  fullWidthSaveButton: {
    height: sv(52),
    borderRadius: s(18),
    backgroundColor: COLORS.toolsGold ?? COLORS.gold,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s(8),
    marginTop: sv(24),
  },
  fullWidthSaveButtonText: {
    color: COLORS.black,
    fontSize: sf(13.5),
    fontWeight: '900',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: s(26),
    borderRadius: s(24),
    backgroundColor: 'rgba(10, 9, 17, 0.82)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.toolsCardBorder ?? COLORS.borderDeep,
    marginTop: sv(8),
  },
  emptyTitle: {
    color: COLORS.toolsText ?? COLORS.textPrimary,
    fontSize: sf(17),
    fontWeight: '900',
    marginTop: sv(12),
  },
  emptyText: {
    color: COLORS.toolsTextMuted ?? COLORS.textMuted,
    fontSize: sf(13),
    lineHeight: sf(19),
    textAlign: 'center',
    marginTop: sv(6),
  },
  backToOverviewButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(6),
    paddingHorizontal: s(12),
    paddingVertical: s(9),
    borderRadius: s(999),
    backgroundColor: 'rgba(214,168,79,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(214,168,79,0.24)',
    marginTop: s(-10),
    marginBottom: s(18),
  },

  backToOverviewText: {
    color: COLORS.toolsGold ?? COLORS.gold,
    fontSize: s(13),
    fontWeight: '900',
  },
});
